# Generated by Mia
{
  description = "Mia Agent, the configurable, easy to use, personal AI agent.";

  nixConfig = {
    extra-substituters = [ "https://mastermach50.cachix.org" ];
    extra-trusted-public-keys = [
      "mastermach50.cachix.org-1:tAE8Bm8oMXdo3W+VzuBu2ZahQ03B1Drk4ViZWHcs4j0="
    ];
  };

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    crane.url = "github:ipetkov/crane";
    fenix.url = "github:nix-community/fenix";
  };

  outputs =
    {
      nixpkgs,
      crane,
      fenix,
      ...
    }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forEachSystem = nixpkgs.lib.genAttrs systems;

      makePackages = forEachSystem (
        system:
        let
          pkgs = import nixpkgs { inherit system; };
          fenixComplete = fenix.packages.${system}.complete;
          craneLib = (crane.mkLib pkgs).overrideToolchain fenixComplete.toolchain;
          mia-agent = pkgs.callPackage ./package.nix { inherit craneLib; };
        in
        {
          inherit mia-agent fenixComplete pkgs;
        }
      );
    in
    {
      packages = forEachSystem (
        system:
        let
          madePkgs = makePackages.${system};
        in
        {
          default = madePkgs.mia-agent.package;
          ${system} = madePkgs.mia-agent.package;
          nixpkgs-compat = madePkgs.pkgs.callPackage ./nixpkgs-package.nix { };
        }
      );

      devShell = forEachSystem (
        system:
        let
          madePkgs = makePackages.${system};
        in
        madePkgs.pkgs.mkShell {
          name = "mia-shell";

          nativeBuildInputs = with madePkgs; [
            fenixComplete.toolchain
            fenixComplete.rust-analyzer
            # mia-agent.package
          ];

          buildInputs = madePkgs.mia-agent.runtimeDeps;
        }
      );
    };
}
