use std::collections::HashMap;
use std::result::Result::Ok;

use anyhow::{Context, Result};
use futures_util::StreamExt;
use log::{debug, error, trace, warn};
use reqwest::{
    Client,
    header::{AUTHORIZATION, HeaderMap, REFERER},
};
use serde::{Deserialize, Serialize};
use serde_json::json;
use tokio_util::sync::CancellationToken;

use crate::config::AppConfig;
use crate::{agent_tools::ToolRegistry, setup::Providers};

/// A tool call that is generated by the assistant
#[derive(Serialize, Deserialize, Clone)]
pub struct ToolCall {
    pub id: String,
    #[serde(rename = "type")]
    pub type_field: String,
    pub function: FunctionCall,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct FunctionCall {
    pub name: String,
    pub arguments: String, // The arguments are a JSON string that may or may not be valid
}

#[derive(Serialize, Deserialize, Clone)]
pub struct TokenUsage {
    pub prompt_tokens: u64,
    pub completion_tokens: u64,
    pub total_tokens: u64,
}

/// A message structure that can hold any type of message from any role
#[derive(Serialize, Deserialize, Clone)]
pub struct Message {
    pub role: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<TokenUsage>,
}

impl Message {
    pub fn new(role: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            role: role.into(),
            reasoning: None,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: None,
            usage: None,
        }
    }
    pub fn new_tool_call_response(
        tool_call_id: impl Into<String>,
        content: impl Into<String>,
    ) -> Self {
        Self {
            role: "tool".to_string(),
            reasoning: None,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: Some(tool_call_id.into()),
            usage: None,
        }
    }
}

/// A partial message struct, that helps in outputing streamed content
#[derive(Serialize, Deserialize, Clone)]
pub struct PartialMessage {
    pub role: String,
    pub reasoning_chunk_index: i64,
    pub reasoning: Option<String>,
    pub content_chunk_index: i64,
    pub content: Option<String>,
}

#[derive(Serialize, Deserialize, Default, Clone)]
pub struct History {
    pub messages: Vec<Message>,
}

impl History {
    pub fn new() -> Self {
        Self {
            messages: Vec::new(),
        }
    }

    pub fn set_system_prompt(&mut self, prompt: String) {
        if let Some(message) = self.messages.first()
            && message.role == "system"
        {
            self.messages[0] = Message::new("system", prompt);
        } else {
            self.messages.insert(0, Message::new("system", prompt));
        }
    }

    pub fn add_message(&mut self, message: Message) {
        self.messages.push(message);
    }
}

pub enum Completion {
    Completed(Message),
    Cancelled,
}

pub async fn completion(
    history: &History,
    session_id: &str,
    stream: bool,
    cancel: &CancellationToken,
    on_status_update: impl Fn(&str),
    on_partial_message: impl Fn(&PartialMessage),
) -> Result<Completion> {
    // Get the http client, with the default headers required to identify this as mia agent
    let client = Client::builder()
        .default_headers(get_default_headers())
        .build()?;

    let provider_name = AppConfig::global().model.provider.clone();
    let provider = Providers::from_name(&provider_name).unwrap();

    // Generate the payload
    let mut payload = json!({
        "messages": history.messages,
        "model": AppConfig::global().model.name,
        "reasoning_effort": AppConfig::global().model.reasoning,
        "tools": ToolRegistry::schema(),
        "stream": stream
    });
    if provider == Providers::Openrouter {
        payload["session_id"] = json! { session_id }
    }

    // Generate the request url
    let request_url = AppConfig::global().model.base_url.clone() + "/chat/completions";

    // Send the request
    let response = tokio::select! {
        res = client.post(request_url).json(&payload).send() => {
            res.context("Failed to send streaming chat completion request")?
        },
        _ = cancel.cancelled() => {
            return Ok(Completion::Cancelled);
        }
    };

    // Response status is returned first
    debug!("Response Status: {}", response.status());

    // If the status shows some errors then bail
    if !response.status().is_success() {
        let status = response.status();
        let json = response.json::<serde_json::Value>().await?;
        error!("API request failed with status {}", status);
        error!("Response: {:?}", json);
        anyhow::bail!("API request failed with status {}", status);
    }

    // If the status is success then mark the assistant as thinking
    on_status_update("Thinking");

    // If the response is not to be streamed then no complex logic is required.
    // Simply return the whole message content
    if !stream {
        // Cancellation can be made during json parsing
        let content = tokio::select! {
            res = response.json::<serde_json::Value>() => {
                res.context("Failed to read response body")?
            },
            _ = cancel.cancelled() => {
                return Ok(Completion::Cancelled);
            }
        };

        trace!("Response Content: {:?}", content);

        // Decode the message into a Message struct and return it
        let message: Message = serde_json::from_value(content["choices"][0]["message"].clone())
            .context("Failed to decode assistant message")?;

        // Decode the usage as option
        let usage = serde_json::from_value::<TokenUsage>(content["usage"].clone()).ok();

        let message = Message { usage, ..message };

        return Ok(Completion::Completed(message));
    }

    // Define some variables to accumulate the streamed data
    let mut full_content = String::new();
    let mut full_reasoning = String::new();
    let mut tool_calls_map: HashMap<usize, ToolCall> = HashMap::new();
    let mut usage: Option<TokenUsage> = None;

    // Get the bytestream, and a buffer for leftover content
    let mut byte_stream = response.bytes_stream();
    let mut leftover = String::new();

    // Keep track of the chunk index
    let mut reasoning_chunk_index = -1;
    let mut content_chunk_index = -1;

    // Loop until the whole response has been received
    'stream: loop {
        // Check for cancellation before processing
        let chunk = tokio::select! {
            chunk = byte_stream.next() => chunk,
            _ = cancel.cancelled() => return Ok(Completion::Cancelled),
        };

        // Break if chuck is None
        let Some(chunk) = chunk else {
            break;
        };

        // Get the text from the chunk
        let bytes = chunk.context("Failed to read stream chunk")?;
        let text = std::str::from_utf8(&bytes).context("Stream chunk is not valid utf-8")?;

        // Put the text into the buffer
        leftover.push_str(text);

        // When a full line is received process it, otherwise wait until a full line is recieved
        while let Some(newline_idx) = leftover.find('\n') {
            // Get the string till the \n as the line, keep the rest in the buffer
            let line = leftover[..newline_idx].trim_end_matches('\r').to_string();
            leftover = leftover[newline_idx + 1..].to_string();

            trace!("SSE: {:?}", line);

            // If the line is empty, skip processing
            if line.is_empty() {
                continue;
            }

            // If there is no data section, skip processing
            let data = if let Some(d) = line.strip_prefix("data: ") {
                d
            } else {
                continue;
            };

            // If "[DONE]" is received that means the stream is done, break out of the stream loop
            if data == "[DONE]" {
                break 'stream;
            }

            // If the data could not be parsed as json, skip processing
            let Ok(chunk_json) = serde_json::from_str::<serde_json::Value>(data) else {
                warn!("Could not parse streamed data as JSON: {:?}", data);
                continue;
            };

            // grab the usage if it exists
            if chunk_json["usage"].is_object() {
                if let Ok(u) = serde_json::from_value::<TokenUsage>(chunk_json["usage"].clone()) {
                    usage = Some(u);
                }
            }

            // Get the delta section of the streamed data
            let delta = &chunk_json["choices"][0]["delta"];

            // If there is some reasoning data then append it to the full reasoning
            // and do any processing necessary
            if let Some(reasoning) = delta["reasoning"].as_str().filter(|s| !s.is_empty()) {
                reasoning_chunk_index += 1;

                let reasoning = if reasoning_chunk_index == 0 {
                    reasoning.trim_start_matches('\n')
                } else {
                    reasoning
                };

                full_reasoning.push_str(reasoning);

                on_partial_message(&PartialMessage {
                    role: "assistant".to_string(),
                    reasoning_chunk_index: reasoning_chunk_index,
                    reasoning: Some(reasoning.to_string()),
                    content_chunk_index: content_chunk_index,
                    content: None,
                });
            }

            // If there is some content then append it to the full content
            // and do any processing necessary
            if let Some(content) = delta["content"].as_str().filter(|s| !s.is_empty()) {
                content_chunk_index += 1;

                let content = if content_chunk_index == 0 {
                    content.trim_start_matches('\n')
                } else {
                    content
                };

                full_content.push_str(content);

                on_partial_message(&PartialMessage {
                    role: "assistant".to_string(),
                    reasoning_chunk_index: reasoning_chunk_index,
                    reasoning: None,
                    content_chunk_index: content_chunk_index,
                    content: Some(content.to_string()),
                });
            }

            // If there are any tool calls then accumulate it
            if let Some(tc_deltas) = delta["tool_calls"].as_array() {
                for tc_delta in tc_deltas {
                    let index = tc_delta["index"].as_u64().unwrap_or(0) as usize;
                    let entry = tool_calls_map.entry(index).or_insert_with(|| ToolCall {
                        id: String::new(),
                        type_field: "function".to_string(),
                        function: FunctionCall {
                            name: String::new(),
                            arguments: String::new(),
                        },
                    });

                    if let Some(id) = tc_delta["id"].as_str() {
                        entry.id.push_str(id);
                    }
                    // if let Some(t) = tc_delta["type"].as_str() {
                    //     entry.type_field = t.to_string(); // Won't this ever be a cuttoff partial value, also won't this always need to be "function"
                    // }
                    if let Some(name) = tc_delta["function"]["name"].as_str() {
                        entry.function.name.push_str(name);
                    }
                    if let Some(args) = tc_delta["function"]["arguments"].as_str() {
                        entry.function.arguments.push_str(args);
                    }
                }
            }
        }
    }

    // After streaming is finished assemple the tool calls
    let full_tool_calls = if tool_calls_map.is_empty() {
        None
    } else {
        let mut sort_buffer: Vec<(usize, ToolCall)> = tool_calls_map.into_iter().collect();
        sort_buffer.sort_by_key(|(i, _)| *i);
        Some(sort_buffer.into_iter().map(|(_, tc)| tc).collect())
    };

    let message = Message {
        role: "assistant".to_string(),
        reasoning: if full_reasoning.is_empty() {
            None
        } else {
            Some(full_reasoning)
        },
        content: if full_content.is_empty() {
            None
        } else {
            Some(full_content)
        },
        tool_calls: full_tool_calls,
        tool_call_id: None,
        usage,
    };

    Ok(Completion::Completed(message))
}

#[derive(Serialize, Deserialize)]
pub struct Model {
    pub id: String,
    pub name: Option<String>,
    pub context_length: Option<i64>,
    pub architecture: Option<ModelArch>,
    pub pricing: Option<ModelPricing>,
}

#[derive(Serialize, Deserialize)]
pub struct ModelArch {
    pub input_modalities: Vec<String>,
    pub modality: Option<String>,
    pub output_modalities: Vec<String>,
}

#[derive(Serialize, Deserialize)]
pub struct ModelPricing {
    pub completion: String,
    pub prompt: String,
}

/// Get list of available models from the API
pub async fn models(base_url: &str, api_key_name: Option<&str>) -> Result<Vec<Model>> {
    let client = Client::new();

    dotenvy::from_path(AppConfig::internal().env_file.clone())?;

    let params = [
        ("output_modalities", "text"),
        ("sort", "pricing-low-to-high"),
    ];

    let mut request = client.get(base_url.to_owned() + "/models").query(&params);

    if let Some(api_key_name) = api_key_name {
        request = request.header(
            AUTHORIZATION,
            format!("Bearer {}", std::env::var(api_key_name)?),
        )
    }

    let response = request.send().await?;

    debug!("Response Status: {}", response.status());

    if !response.status().is_success() {
        let status = response.status();
        let json = response.json::<serde_json::Value>().await?;
        error!("API request failed with status {}", status);
        error!("Response: {:?}", json);
        anyhow::bail!("API request failed with status {}", status);
    }

    let content = response.json::<serde_json::Value>().await?;
    trace!("Response Content: {:?}", content);

    let models: Vec<Model> = serde_json::from_value(content["data"].clone())
        .context("Failed to decode assistant message")?;

    Ok(models)
}

/// Get the default headers used by every request
fn get_default_headers() -> HeaderMap {
    let mut headers = HeaderMap::new();
    headers.insert(REFERER, "https://mathewma3.in".parse().unwrap());

    let provider_name = AppConfig::global().model.provider.clone();
    let provider = Providers::from_name(&provider_name).unwrap();

    if provider != Providers::Local {
        headers.insert(
            AUTHORIZATION,
            format!(
                "Bearer {}",
                std::env::var(provider.api_key_name().unwrap()).unwrap()
            )
            .parse()
            .unwrap(),
        );
    }

    if AppConfig::global().model.provider == "openrouter" {
        headers.insert("X-OpenRouter-Title", "Mia Agent".parse().unwrap());
        headers.insert(
            "X-OpenRouter-Categories",
            "cli-agent,personal-agent".parse().unwrap(),
        );
    }

    headers
}
