use log::{debug, error, trace};
use reqwest::{Client, header::{AUTHORIZATION, REFERER, HeaderMap}};
use anyhow::{Context, Ok, Result};
use serde::{Deserialize, Serialize};
use serde_json::json;
use tokio_util::sync::CancellationToken;

use crate::config::AppConfig;
use crate::agent_tools::ToolRegistry;

/// A tool call that is generated by the assistant
#[derive(Serialize, Deserialize, Clone)]
pub struct ToolCall {
    pub id: String,
    #[serde(rename = "type")]
    pub type_field: String,
    pub function: FunctionCall,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct FunctionCall {
    pub name: String,
    pub arguments: String // The arguments are a JSON string that may or may not be valid
}

/// A message structure that can hold any type of message from any role
#[derive(Serialize, Deserialize, Clone)]
pub struct Message {
    pub role: String,
    pub reasoning: Option<String>,
    pub content: Option<String>,
    pub tool_calls: Option<Vec<ToolCall>>,
    pub tool_call_id: Option<String>,
}

impl Message {
    pub fn new(role: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            role: role.into(),
            reasoning: None,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: None,
        }
    }
    pub fn new_tool_call_response(tool_call_id: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            role: "tool".to_string(),
            reasoning: None,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: Some(tool_call_id.into()),
        }
    }
}

#[derive(Serialize, Deserialize)]
pub struct History {
    pub messages: Vec<Message>
}

impl History {
    pub fn new() -> Self {
        Self {
            messages: Vec::new()
        }
    }

    pub fn set_system_prompt(&mut self, prompt: String) {
        if let Some(message) = self.messages.get(0) {
            if message.role == "system" {
                self.messages[0] = Message::new("system", prompt);
            }
        } else {
            self.messages.insert(0, Message::new("system", prompt));
        }
    }

    pub fn add_message(&mut self, message: Message) {
        self.messages.push(message);
    }
}

/// Simply calls the chat/completion endpoint with a given history and returns the response
pub async fn completion(history: &History, cancel: &CancellationToken) -> Result<Message> {
    let client = Client::builder()
        .default_headers(get_default_headers())
        .build()?;

    let payload = json!({
        "messages": history.messages,
        "model": AppConfig::global().model.name,
        "reasoning": {
            "effort": AppConfig::global().model.reasoning
        },
        "tools": ToolRegistry::schema()
    });

    let request = client.post(AppConfig::global().model.base_url.clone() + "/chat/completions")
        .json(&payload)
        .send();

    // Ctrl-C is acceptable while waiting for a response headers
    let response = tokio::select! {
        res = request => res.context("Failed to send chat completion request")?,
        _ = cancel.cancelled() => anyhow::bail!("Request cancelled")
    };

    debug!("Response Status: {}", response.status());

    if !response.status().is_success() {
        let status = response.status();
        let json = response.json::<serde_json::Value>().await?;
        error!("API request failed with status {}", status);
        error!("Response: {:?}", json);
        anyhow::bail!("API request failed with status {}", status);
    }

    // Ctrl-C is acceptable while waiting for a response body
    let content = tokio::select! {
        res = response.json::<serde_json::Value>() => res.context("Failed to read response body")?,
        _ = cancel.cancelled() => anyhow::bail!("Request cancelled")
    };
    trace!("Response Content: {:?}", content);

    let message: Message = serde_json::from_value(content["choices"][0]["message"].clone())
        .context("Failed to decode assistant message")?;

    Ok(message)
}


#[derive(Serialize, Deserialize)]
pub struct Model {
    pub id: String,
    pub name: Option<String>,
    pub context_length: Option<i64>,
    pub architecture: Option<ModelArch>,
    pub pricing: Option<ModelPricing>,
}

#[derive(Serialize, Deserialize)]
pub struct ModelArch {
    pub input_modalities: Vec<String>,
    pub modality: Option<String>,
    pub output_modalities: Vec<String>,
}

#[derive(Serialize, Deserialize)]
pub struct ModelPricing {
    pub completion: String,
    pub prompt: String,
}

/// Get list of available models from the API
pub async fn models() -> Result<Vec<Model>> {
    let client = Client::builder()
        .default_headers(get_default_headers())
        .build()?;

    let params = [
        ("output_modalities", "text"),
        ("sort", "pricing-low-to-high"),
    ];

    let response = client.get(AppConfig::global().model.base_url.clone() + "/models")
        .query(&params)
        .send()
        .await?;

    debug!("Response Status: {}", response.status());

    if !response.status().is_success() {
        let status = response.status();
        let json = response.json::<serde_json::Value>().await?;
        error!("API request failed with status {}", status);
        error!("Response: {:?}", json);
        anyhow::bail!("API request failed with status {}", status);
    }

    let content = response.json::<serde_json::Value>().await?;
    trace!("Response Content: {:?}", content);

    let models: Vec<Model> = serde_json::from_value(content["data"].clone())
        .context("Failed to decode assistant message")?;

    Ok(models)
}

/// Get the default headers used by every request
fn get_default_headers() -> HeaderMap {
    let mut headers = HeaderMap::new();
    headers.insert(
        REFERER,
        "https://mathewma3.in".parse().unwrap()
    );

    if AppConfig::global().model.base_url.contains("openrouter.ai") {
        headers.insert(
            AUTHORIZATION,
            format!("Bearer {}", std::env::var("OPENROUTER_API_KEY").unwrap()).parse().unwrap()
        );
        headers.insert(
            "X-OpenRouter-Title",
            "Mia Agent".parse().unwrap()
        );
    }

    headers
}