use log::{debug, error, trace};
use reqwest::{Client, header::{AUTHORIZATION, REFERER, HeaderMap}};
use anyhow::{Context, Ok, Result};
use serde::{Deserialize, Serialize};
use serde_json::json;

use crate::config::AppConfig;
use crate::agent_tools::ToolRegistry;

/// A tool call that is generated by the assistant
#[derive(Serialize, Deserialize, Clone)]
pub struct ToolCall {
    pub id: String,
    #[serde(rename = "type")]
    pub type_field: String,
    pub function: FunctionCall,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct FunctionCall {
    pub name: String,
    pub arguments: serde_json::Value,
}

/// A message structure that can hold any type of message from any role
#[derive(Serialize, Deserialize, Clone)]
pub struct Message {
    pub role: String,
    pub reasoning: Option<String>,
    pub content: Option<String>,
    pub tool_calls: Option<Vec<ToolCall>>,
    pub tool_call_id: Option<String>,
}

impl Message {
    pub fn new(role: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            role: role.into(),
            reasoning: None,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: None,
        }
    }
    pub fn new_tool_call_response(tool_call_id: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            role: "tool".to_string(),
            reasoning: None,
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: Some(tool_call_id.into()),
        }
    }
}

#[derive(Serialize, Deserialize)]
pub struct History {
    pub messages: Vec<Message>
}

impl History {
    pub fn new() -> Self {
        Self {
            messages: Vec::new()
        }
    }

    pub fn set_system_prompt(&mut self, prompt: String) {
        self.messages.insert(0, Message::new("system", prompt));
    }

    pub fn add_message(&mut self, message: Message) {
        self.messages.push(message);
    }
}

/// Simply calls the chat/completion endpoint with a given history and returns the response
pub async fn completion(history: &History) -> Result<Message> {
    let mut headers = HeaderMap::new();
    headers.insert(
        AUTHORIZATION,
        format!("Bearer {}", std::env::var("OPENROUTER_API_KEY").unwrap()).parse().unwrap()
    );
    headers.insert(
        REFERER,
        "https://mathewma3.in".parse().unwrap()
    );
    headers.insert(
        "X-OpenRouter-Title",
        "Mia Agent".parse().unwrap()
    );

    let client = Client::builder()
        .default_headers(headers)
        .build()?;

    let payload = json!({
        "messages": history.messages,
        "model": AppConfig::global().model.name,
        "reasoning": {
            "effort": AppConfig::global().model.reasoning
        },
        "tools": ToolRegistry::schema()
    });

    let response = client.post("https://openrouter.ai/api/v1/chat/completions")
        .json(&payload)
        .send()
        .await
        .context("Failed to parse API response")?;
    debug!("Response Status: {}", response.status());

    if !response.status().is_success() {
        let status = response.status();
        let json = response.json::<serde_json::Value>().await?;
        error!("API request failed with status {}", status);
        error!("Response: {:?}", json);
        anyhow::bail!("API request failed with status {}", status);
    }

    let content = response.json::<serde_json::Value>().await?;
    trace!("Response Content: {:?}", content);

    let message: Message = serde_json::from_value(content["choices"][0]["message"].clone())
        .context("Failed to decode assistant message")?;

    Ok(message)
}

