// This file was AI generated by Mia

use std::fs;
use serde_json::json;

use crate::agent_tools::Tool;

#[derive(Debug)]
pub struct FileReader;

impl Tool for FileReader {
    fn name(&self) -> String { "file_read".to_string() }
    fn icon(&self) -> String { "📖".to_string() }
    fn schema(&self) -> serde_json::Value {
        json!({
            "type": "function",
            "function": {
                "name": "file_read",
                "description": "Read a file from the filesystem. Returns the content or an error message.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "path": {
                            "type": "string",
                            "description": "The file path to read (relative to current directory)"
                        }
                    },
                    "required": ["path"]
                }
            }
        })
    }
    fn execute(&self, args: serde_json::Value) -> serde_json::Value {
        let path = args["path"].as_str()
            .expect("Path argument not found");
        
        match fs::read_to_string(path) {
            Ok(content) => {
                let preview = if content.len() > 10000 {
                    format!("{}... {} more characters (content > 10000 characters)", 
                        &content[..10000], content.len() - 10000)
                } else {
                    content.clone()
                };
                
                json!({
                    "status": "success",
                    "path": path,
                    "size": content.len(),
                    "content": preview,
                    "full_content": content.len() <= 10000
                })
            },
            Err(e) => json!({
                "status": "error",
                "message": format!("I couldn't read that file, babe! Error: {}", e)
            })
        }
    }
}
