// This file was AI generated by Mia

use colored::Colorize;
use serde_json::json;

use crate::{agent_tools::Tool, utils::ask_permission};

#[derive(Debug)]
pub struct Python;
impl Tool for Python {
    fn name(&self) -> String { "python".to_string() }
    fn icon(&self) -> String { "🐍".to_string() }
    fn short(&self, args: serde_json::Value) -> String {
        args["code"].as_str()
            .unwrap_or_default().to_string()
    }
    fn is_available(&self) -> bool {
        std::process::Command::new("which")
            .arg("python3")
            .output()
            .expect("Failed to execute 'which'")
            .status
            .success()
    }
    fn schema(&self) -> serde_json::Value {
        json!({
            "type": "function",
            "function": {
                "name": &self.name(),
                "description": "Execute Python 3 code",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string",
                            "description": "The Python code to execute"
                        }
                    },
                    "required": [ "code" ]
                }
            }
        })
    }
    fn execute(&self, args: serde_json::Value) -> serde_json::Value {
        let code = args["code"].as_str()
            .expect("Code argument not found");
        if ask_permission("Execute Python?".red(), code) {
            let output = std::process::Command::new("python3")
                .arg("-c")
                .arg(code)
                .output()
                .expect("Failed to execute Python code");
            println!("{}", String::from_utf8(output.stdout.clone()).unwrap());
            json!({
                "status": "success",
                "command_status_code": output.status.code().unwrap(),
                "output": String::from_utf8(output.stdout).unwrap(),
                "error": String::from_utf8(output.stderr).unwrap()
            })
        } else {
            json!({
                "status": "error",
                "message": "User declined to execute Python code"
            })
        }
    }
}
