// This file was AI generated by Mia

use termimad::crossterm::style::Stylize;
use serde_json::json;

use crate::{agent_tools::Tool, utils::{ask_permission, hilight_text}};

#[cfg(unix)]
static PYTHON_CMD: &str = "python3";

#[cfg(windows)]
static PYTHON_CMD: &str = "python";

#[derive(Debug)]
pub struct Python;
impl Tool for Python {
    fn name(&self) -> String { "python".to_string() }
    fn icon(&self) -> String { "🐍".to_string() }
    fn short(&self, args: serde_json::Value) -> String {
        args["code"].as_str()
            .unwrap_or_default().to_string()
    }
    fn availability(&self) -> Result<(), String> {
        which::which(PYTHON_CMD)
            .map(|_| ())
            .map_err(|_| "python3 not found".to_string())
    }
    fn schema(&self) -> serde_json::Value {
        json!({
            "type": "function",
            "function": {
                "name": &self.name(),
                "description": "Execute Python 3 code",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string",
                            "description": "The Python code to execute"
                        }
                    },
                    "required": [ "code" ]
                }
            }
        })
    }
    fn execute(&self, args: serde_json::Value) -> serde_json::Value {
        let code = args["code"].as_str()
            .expect("Code argument not found");

        let colored_code = hilight_text("something.py", code);

        if ask_permission("Execute Python?".red(), &colored_code) {
            let output = std::process::Command::new(PYTHON_CMD)
                .arg("-c")
                .arg(code)
                .output()
                .expect("Failed to execute Python code");
            println!("{}", String::from_utf8(output.stdout.clone()).unwrap());
            json!({
                "status": "success",
                "command_status_code": output.status.code().unwrap(),
                "output": String::from_utf8(output.stdout).unwrap(),
                "error": String::from_utf8(output.stderr).unwrap()
            })
        } else {
            json!({
                "status": "error",
                "message": "User declined to execute Python code"
            })
        }
    }
}
